# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: SEUNGWOO'S TECH LOG
email: seungwoo321@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
# github_username:  Seungwoo321
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: contrast
paginate: 5 # amount of posts to show
paginate_path: /page:num/
author:
  name: Seungwoo Lee
  avatar: /assets/images/avatar.jpeg
  bio: 1인 개발자로 성장하는 것을 목표로 공부하는 프론트엔드 개발자입니다.
  location: Seoul
  email: seungwoo321@gmail.com
  github: Seungwoo321
  linkedin: seungwoo321
og_image: /assets/images/template.png
include:
  - .htaccess
  - _pages
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - package-lock.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
# Analytics
# google_analytics: true
analytics:
  provider               : "google-gtag"
  google:
    tracking_id          : G-DLLRFBXZCW

# Google AdSense
adsense:
  ad_client: "ca-pub-7701657858733816"
  data_ad_format: "auto"
  data_full_width_responsive: "true"

encoding: "utf-8"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
